all:
	ghc --make execTP.hs

fac:
	ghc --make facTerminale.hs
	ghc --make facNonTerminale.hs

fibo:
	ghc --make fiboTerminale.hs
	ghc --make fiboNonTerminale.hs

clean:
	rm *.hi
	rm *.o
	rm execTP
	rm facTerminale
	rm facNonTerminale
